$('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    nav:true,
    dots: false,
    responsive:{
        0:{
            items:2
        },
        767:{
            items:3
        },
        992:{
            item:3
        },
        1200:{
            items:4
        }
    }
})